#!/usr/bin/env python

Import('env')

thirdparty_BroLib_dir = "#thirdparty/BroLib/"
thirdparty_BroLib_sources = [
	"Gat.cpp",
	"Gnd.cpp",
	"GrfFileSystemHandler.cpp",
	"Map.cpp",
	"Rsm.cpp",
	"Rsw.cpp",
	"grflib/grf.c",
	"grflib/grfcrypt.c",
	"grflib/grfsupport.c",
	"grflib/rgz.c",
]
thirdparty_BroLib_sources = [thirdparty_BroLib_dir + file for file in thirdparty_BroLib_sources]
env.add_source_files(env.core_sources, thirdparty_BroLib_sources)
env.Append(CPPPATH=["#thirdparty/BroLib", "#thirdparty/BroLib/grflib"])
